---
title: 'Welcome to C-POT'
author: 'Yioryos Nardis'
date: '2019-08-26'
slug: welcome
categories: []
tags: 
 - general
subtitle: ''
description: ''
image: ''
---

Welcome to Cyprus Public Opinion Trends (C-POT)!  
<br>
Through this blog I’ll be providing non-partisan information and quantitative analysis on Cypriots’ attitudes towards the social, political and cultural issues their society faces. Its objective is to make Cypriots’ views more accessible to the general public, journalists, academics and political professionals. Discussion of Greek-Cypriot and Turkish-Cypriot public opinion is a central feature of this endeavor. Quantitative analyses are based on publicly available survey data and to ensure transparency, information to replicate all analyses is provided. Occasional contributions from guest writers will also be featured.  
<br>
I hope you enjoy the content! Please feel free to send me comments, suggestions, and ideas. <br><br>
_Contact_  
Email: <a href="mailto:yioryos@gmail.com">yioryos@gmail.com</a>  
[LinkedIn](https://www.linkedin.com/in/yioryosnardis){target="_blank"}  
<br>
Yioryos Nardis  
Senior Researcher  
Institute for Social Research-Center for Political Studies  
University of Michigan (USA)  
<br>

—
<br><br>
Καλώς ορίσατε στις Τάσεις της Κοινής Γνώμης στην Κύπρο (C-POT)!  
<br>
Μέσο αυτού του ιστολογίου θα παρέχω ακομμάτιστες πληροφορίες και ποσοτική ανάλυση για τις στάσεις των Κυπρίων σχετικά με τα κοινωνικά, πολιτικά και πολιτιστικά θέματα που αντιμετωπίζει η κοινωνία τους. Ο στόχος του είναι να κάνει τις απόψεις των Κυπρίων πιο προσιτές για το ευρύτερο κοινό, δημοσιογράφους, ακαδημαϊκούς και επαγγελματίες της πολιτικής. Η συζήτηση της κοινής γνώμης των Ελληνοκυπρίων και Τουρκοκυπρίων θα είναι σημαντικό χαρακτηριστικό αυτής της προσπάθειας. Η ποσοτικές αναλύσεις θα βασίζονται σε δημοσίως διαθέσιμα δεδομένα από έρευνες επισκόπησης και για λόγους διαφάνειας, πληροφορίες που θα επιτρέπουν την αναπαραγωγή όλων των αναλύσεων θα δίνονται. Επίσης, κάποτε θα περιέχει και συνεισφορές από φιλοξενούμενους συγγραφείς.<br>
<br>
Ελπίζω να σας αρέσει το περιεχόμενο! Παρακαλώ μην διστάσετε να μου στείλετε σχόλια, εισηγήσεις και ιδέες.
<br><br>
_Επικοινωνία  _  
Email: <a href="mailto:yioryos@gmail.com">yioryos@gmail.com</a>  
[LinkedIn](https://www.linkedin.com/in/yioryosnardis/){target="_blank"}      
<br>
Γιώργος Ναρδής  
Ανώτερος Ερευνητής  
Ινστιτούτο Κοινωνικής Έρευνας-Κέντρο Πολιτικών Με  λετών
Πανεπιστήμιο του Μίσιγκαν (ΗΠΑ).
<br>

—
<br><br>
Kıbrıs Kamuoyu Trendleri’ne (C-POT) hoş geldiniz!  
<br>
Blog, Kıbrıslıların toplumda karşılaştıkları sosyal, politik ve kültürel meselelere yönelik tutumları hakkında tarafsız bilgi ve sayısal analiz sağlamaktadır. Blogun amacı, Kıbrıslıların görüşlerini halk, gazeteciler, akademisyenler ve politika profesyonelleri tarafından daha erişilebilir hale getirmektir. Kamuoyunda Kıbrıslı-Rum ve Kıbrıslı-Türk fikrinin tartışılması, bu girişimin merkezi özeliğini oluşturmaktadır. Buradaki sayısal analizler kamuya açık anket verilerine dayanmaktadır. Şeffaflık açısından, tüm analizlerin tekrarlanabileceği yazılım kodu herkesin kullanımına açıktır. Zaman zaman konuk yazarların katkıları da sunulacaktır.  
<br>
Umarım içeriğin tadını çıkarırsınız! Lütfen yorum, öneri ve fikirleriniz için benimle iletişime geçmekten çekinmeyiniz.  <br>

_İletişim    _  
Email: <a href="mailto:yioryos@gmail.com">yioryos@gmail.com</a>  
[LinkedIn](https://www.linkedin.com/in/yioryosnardis/){target="_blank"}  

Yioryos Nardis    
Kıdemli Araştırmacısı    
Sosyal Araştırmalar Enstitüsü-Siyasal Çalışmalar Merkezi    
Michigan Üniversitesi (ABD)

