---
title: About  
author: ''  
date: '2019-08-08'  
slug: about  
categories: []  
tags: []
---

Welcome to Cyprus Public Opinion Trends (C-POT)!   
<br>
The blog provides non-partisan information and quantitative analysis on Cypriots’ attitudes towards the social, political and cultural issues their society faces. Its objective is to make Cypriots’ views more accessible to the general public, journalists, academics and political professionals. Discussion of Greek-Cypriot and Turkish-Cypriot public opinion is a central feature of this endeavor. Quantitative analyses are based on publicly available survey data and to ensure transparency software code to replicate all analyses is provided. Occasional contributions from guest writers will also be featured.  
<br>
The blog is owned and maintained by Yioryos Nardis, Senior Researcher at the Institute for Social Research-Center for Political Studies at the University of Michigan.  
<br>
I hope you enjoy the content! Please feel free to send me comments, suggestions, and ideas. <br>

_Contact_  
Email: <a href="mailto:yioryos@gmail.com">yioryos@gmail.com</a>  
[LinkedIn](https://www.linkedin.com/in/yioryosnardis){target="_blank"} 
<br><br>
Disclaimer:
This blog is provided for information purposes only. Anyone using and acting on information from it does so at their own risk and liability.  
<br>
—  
<br>
__Περί Ιστολογίου  __  
Καλώς ορίσατε στις Τάσεις της Κοινής Γνώμης στην Κύπρο (Cyprus Public Opinion Trends – C-POT)!  

Μέσο αυτού του ιστολογίου θα παρέχω ακομμάτιστες πληροφορίες και ποσοτική ανάλυση για τις στάσεις των Κυπρίων σχετικά με τα κοινωνικά, πολιτικά και πολιτιστικά θέματα που αντιμετωπίζει η κοινωνία τους. Ο στόχος του είναι να κάνει τις απόψεις των Κυπρίων πιο προσιτές για το ευρύτερο κοινό, δημοσιογράφους, ακαδημαϊκούς και επαγγελματίες της πολιτικής. Η συζήτηση της κοινής γνώμης των Ελληνοκυπρίων και Τουρκοκυπρίων θα είναι σημαντικό χαρακτηριστικό αυτής της προσπάθειας. Η ποσοτικές αναλύσεις θα βασίζονται σε δημοσίως διαθέσιμα δεδομένα από έρευνες επισκόπησης και για λόγους διαφάνειας, πληροφορίες που θα επιτρέπουν την αναπαραγωγή όλων των αναλύσεων θα δίνονται. Επίσης, κάποτε θα περιέχει και συνεισφορές από φιλοξενούμενους συγγραφείς.  
<br>
Το ιστολόγιο διατηρείται από τον Γιώργο Ναρδή, Ανώτερος Ερευνητής στο Ινστιτούτο Κοινωνικής Έρευνας-Κέντρο Πολιτικών Μελετών στο Πανεπιστήμιο του Μίσιγκαν (ΗΠΑ).  
<br>
Ελπίζω να σας αρέσει το περιεχόμενο. Παρακαλώ μην διστάσετε να μου στείλετε σχόλια, εισηγήσεις και ιδέες.
<br><br>
_Επικοινωνία_  
Email: <a href="mailto:yioryos@gmail.com">yioryos@gmail.com</a>  
[LinkedIn](https://www.linkedin.com/in/yioryosnardis){target="_blank"} 
<br><br>
Αποποίηση ευθυνών:
Αυτό το ιστολόγιο παρέχεται μόνο για ενημερωτικούς σκοπούς. Όποιος χρησιμοποιήσει πληροφορίες από το ιστολόγιο, το πράττει με δική του ευθύνη.

—

__Hakkımızda__  
Kıbrıs Kamuoyu Trendleri’ne (C-POT) hoş geldiniz!  
<br>
Blog, Kıbrıslıların toplumda karşılaştıkları sosyal, politik ve kültürel meselelere yönelik tutumları hakkında tarafsız bilgi ve sayısal analiz sağlamaktadır. Blogun amacı, Kıbrıslıların görüşlerini halk, gazeteciler, akademisyenler ve politika profesyonelleri tarafından daha erişilebilir hale getirmektir. Kamuoyunda Kıbrıslı-Rum ve Kıbrıslı-Türk fikrinin tartışılması, bu girişimin merkezi özeliğini oluşturmaktadır. Buradaki sayısal analizler kamuya açık anket verilerine dayanmaktadır. Şeffaflık açısından, tüm analizlerin tekrarlanabileceği yazılım kodu herkesin kullanımına açıktır. Zaman zaman konuk yazarların  katkıları da sunulacaktır.  
<br>
Blog, Michigan Üniversitesi Sosyal Araştırmalar Enstitüsü, Siyasal Çalışmalar Merkezi kıdemli araştırmacısı Yioryos Nardis tarafından sahiplenilmekte ve sürdürülmektedir.  
<br>
Umarım içeriğin tadını çıkarırsınız! Lütfen yorum, öneri ve fikirleriniz için benimle iletişime geçmekten çekinmeyiniz.  
<br>
_İletişim_  
Email: <a href="mailto:yioryos@gmail.com">yioryos@gmail.com</a>  
[LinkedIn](https://www.linkedin.com/in/yioryosnardis){target="_blank"} 
<br>
 

Yasal Uyarı:  
Bu blog sadece bilgilendirme amaçlıdır. Blogdaki bilgileri kullanan ya da bu bilgilere dayalı hareket eden herkes kendi risk ve sorumluluğunu üstlenmelidir.

 